# Generated by Django 3.0.3 on 2020-02-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('ingredients', models.TextField(default='')),
                ('instructions', models.TextField(default='')),
                ('pic', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
