# Generated by Django 3.0.3 on 2020-02-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal_remedy_finder', '0003_auto_20200219_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='gallery/brown_bottle.jpg', upload_to='gallery'),
        ),
    ]
