# Generated by Django 3.0.3 on 2020-02-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal_remedy_finder', '0005_auto_20200220_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='info',
            new_name='data',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='info_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='herbal_remedy_finder.Info'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
