# Generated by Django 3.0.3 on 2020-02-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal_remedy_finder', '0006_auto_20200220_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='gallery')),
            ],
        ),
    ]
