# Generated by Django 3.0.3 on 2020-02-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal_remedy_finder', '0007_instructional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('pic', models.ImageField(default='gallery/brown_bottle.jpg', upload_to='gallery')),
            ],
        ),
    ]
