# Generated by Django 3.0.3 on 2020-02-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal_remedy_finder', '0008_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructional',
            name='pic',
        ),
    ]
