# Generated by Django 3.0.3 on 2020-02-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal_remedy_finder', '0009_remove_instructional_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructional',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='image', to='herbal_remedy_finder.Image'),
        ),
    ]
