# Generated by Django 3.0.3 on 2020-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbal_remedy_finder', '0010_instructional_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='gallery'),
        ),
    ]
