# Generated by Django 3.0.3 on 2020-02-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbal_remedy_finder', '0011_auto_20200224_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pic',
        ),
    ]
