# Generated by Django 3.0.3 on 2020-02-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herbal_remedy_finder', '0012_remove_recipe_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipe_pic', to='herbal_remedy_finder.Image'),
        ),
    ]
